apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: do-floating-ip
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - patch
      - update
