apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: floating-ip-annotator
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: floating-ip-annotator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: floating-ip-annotator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: k8s.haim.dev/digital-ocean-anchor-ip
                  operator: DoesNotExist
      containers:
        - image: ghcr.io/haimgel/do-floating-ip:main
          command: ["/app/anchor-ip-annotator"]
          # command: ["/bin/sleep", "24h"]
          imagePullPolicy: Always
          name: floating-ip-annotator
          resources: {}
      serviceAccount: do-floating-ip
