apiVersion: v1
kind: Pod
metadata:
  name: test-floating-ip
  namespace: default
spec:
  containers:
    - name: floating-ip-controller
      image: ghcr.io/haimgel/do-floating-ip:main
      imagePullPolicy: Always
      command: ["/bin/sleep", "infinity"]
      env:
        - name: DIGITALOCEAN_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: digital-ocean-token
  serviceAccount: do-floating-ip
  automountServiceAccountToken: true
